apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-pghba-config
data:
  pg_hba.conf: |
    # TYPE  DATABASE        USER            ADDRESS                 METHOD
    local   all             all                                     peer
    hostssl all             all             0.0.0.0/0               md5
    hostssl all             all             ::/0                    md5
    hostnossl all           all             0.0.0.0/0               reject
    hostnossl all           all             ::/0                    reject
