apiVersion: v1
data:
  server.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFRzCCBC+gAwIBAgISA9hk4AcVety1S0b782EYnX0GMA0GCSqGSIb3DQEBCwUA
    MDMxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQwwCgYDVQQD
    EwNSMTAwHhcNMjUwMjE4MTkwMjM0WhcNMjUwNTE5MTkwMjMzWjBHMUUwQwYDVQQD
    EzxtYXN0ZXIxLWtudC1wbGF0Zm9ybS1lbWVyYWxkcy5ub3J0aGV1cm9wZS5jbG91
    ZGFwcC5henVyZS5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCs
    fZSLTyrLJMUgO6arXyPz8ZaLk1vv0iF8kDKejbElRbAKEycJGZc6kFmdpuUqbjOq
    CPufxbvsUbsEL3cH8Z7c300UvJZhycIYWgqgk1VIdAUxn/0Xifop7nELMsPJZz86
    uz82dt55J0n0gyuXtyyOOoYNzjna3mNzNyYuyAkYImsjgC6ssFmdfzndKf1Rz1Xx
    wG+Wm2ykRpSSfzLSUMdXSEYr6/KfVJzKwuc5b5BcSFCvkkMtPLJ2dnaTZGdg95vP
    bhmnNlDO99csNRysdGx59/7NNDOIWRX3vX5acGY9EvpTY747uX9AjFOKiCXT6NPE
    bvMcOtSKd4dvtmOGQRTdAgMBAAGjggI/MIICOzAOBgNVHQ8BAf8EBAMCBaAwHQYD
    VR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0O
    BBYEFN86gqNjQrNtcdy72BCoOBBPTzAiMB8GA1UdIwQYMBaAFLu8w0el5LypxsOk
    cgwQjaI14cjoMFcGCCsGAQUFBwEBBEswSTAiBggrBgEFBQcwAYYWaHR0cDovL3Ix
    MC5vLmxlbmNyLm9yZzAjBggrBgEFBQcwAoYXaHR0cDovL3IxMC5pLmxlbmNyLm9y
    Zy8wRwYDVR0RBEAwPoI8bWFzdGVyMS1rbnQtcGxhdGZvcm0tZW1lcmFsZHMubm9y
    dGhldXJvcGUuY2xvdWRhcHAuYXp1cmUuY29tMBMGA1UdIAQMMAowCAYGZ4EMAQIB
    MIIBAwYKKwYBBAHWeQIEAgSB9ASB8QDvAHYAouMK5EXvva2bfjjtR2d3U9eCW4SU
    1yteGyzEuVCkR+cAAAGVGqZbxQAABAMARzBFAiEAgO544uwHcCvbm+ZetggmSZaS
    UR+VapmpYafv7oXVbK8CIBWEkgKHZjKZiyY3H5STuVr1OONGTPFLVjX0D7czU9qP
    AHUATnWjJ1yaEMM4W2zU3z9S6x3w4I4bjWnAsfpksWKaOd8AAAGVGqZbvQAABAMA
    RjBEAiBywCQdPQQ5R9jpqIdZXIFHe7D4SYh41DSCI53BiXQ6FAIgUt374Vj/AWyJ
    eHWNg4WvqExgrSHxzNI52gA8C2ptKbEwDQYJKoZIhvcNAQELBQADggEBAEHCoh1U
    aWsBeE+JbSbETqy4ZhBTZk/xQlVxxSQOHQRdsjO504OBiWv6ZFfnInB9y9Do7wyf
    ZCTSGVPYlLVvl4YuJB3iAtQiF+/gPVzvkdW2DbVV68gTudzQbp42uINvLFcVCG6P
    VqkEvM5QRbjXZKLBSmVaBb0+DVtsYNPB53MWYtm461TYkRlMHT0gSa6kjtptDfRU
    QuJjnxUxnHgoYmkSfl8abQwBfWrYOqhl7jCmy76BkDV5kYJvuh8KwV0/CsxzF+hz
    N91ZfvlJl+hUBQwcM58v+rF/M8u2Z1xS1LJUQqOowDpM/JQz9h2p3LrVHuLm3rF1
    aCzJfWJiYj8Aqcc=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIFBTCCAu2gAwIBAgIQS6hSk/eaL6JzBkuoBI110DANBgkqhkiG9w0BAQsFADBP
    MQswCQYDVQQGEwJVUzEpMCcGA1UEChMgSW50ZXJuZXQgU2VjdXJpdHkgUmVzZWFy
    Y2ggR3JvdXAxFTATBgNVBAMTDElTUkcgUm9vdCBYMTAeFw0yNDAzMTMwMDAwMDBa
    Fw0yNzAzMTIyMzU5NTlaMDMxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBF
    bmNyeXB0MQwwCgYDVQQDEwNSMTAwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
    AoIBAQDPV+XmxFQS7bRH/sknWHZGUCiMHT6I3wWd1bUYKb3dtVq/+vbOo76vACFL
    YlpaPAEvxVgD9on/jhFD68G14BQHlo9vH9fnuoE5CXVlt8KvGFs3Jijno/QHK20a
    /6tYvJWuQP/py1fEtVt/eA0YYbwX51TGu0mRzW4Y0YCF7qZlNrx06rxQTOr8IfM4
    FpOUurDTazgGzRYSespSdcitdrLCnF2YRVxvYXvGLe48E1KGAdlX5jgc3421H5KR
    mudKHMxFqHJV8LDmowfs/acbZp4/SItxhHFYyTr6717yW0QrPHTnj7JHwQdqzZq3
    DZb3EoEmUVQK7GH29/Xi8orIlQ2NAgMBAAGjgfgwgfUwDgYDVR0PAQH/BAQDAgGG
    MB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATASBgNVHRMBAf8ECDAGAQH/
    AgEAMB0GA1UdDgQWBBS7vMNHpeS8qcbDpHIMEI2iNeHI6DAfBgNVHSMEGDAWgBR5
    tFnme7bl5AFzgAiIyBpY9umbbjAyBggrBgEFBQcBAQQmMCQwIgYIKwYBBQUHMAKG
    Fmh0dHA6Ly94MS5pLmxlbmNyLm9yZy8wEwYDVR0gBAwwCjAIBgZngQwBAgEwJwYD
    VR0fBCAwHjAcoBqgGIYWaHR0cDovL3gxLmMubGVuY3Iub3JnLzANBgkqhkiG9w0B
    AQsFAAOCAgEAkrHnQTfreZ2B5s3iJeE6IOmQRJWjgVzPw139vaBw1bGWKCIL0vIo
    zwzn1OZDjCQiHcFCktEJr59L9MhwTyAWsVrdAfYf+B9haxQnsHKNY67u4s5Lzzfd
    u6PUzeetUK29v+PsPmI2cJkxp+iN3epi4hKu9ZzUPSwMqtCceb7qPVxEbpYxY1p9
    1n5PJKBLBX9eb9LU6l8zSxPWV7bK3lG4XaMJgnT9x3ies7msFtpKK5bDtotij/l0
    GaKeA97pb5uwD9KgWvaFXMIEt8jVTjLEvwRdvCn294GPDF08U8lAkIv7tghluaQh
    1QnlE4SEN4LOECj8dsIGJXpGUk3aU3KkJz9icKy+aUgA+2cP21uh6NcDIS3XyfaZ
    QjmDQ993ChII8SXWupQZVBiIpcWO4RqZk3lr7Bz5MUCwzDIA359e57SSq5CCkY0N
    4B6Vulk7LktfwrdGNVI5BsC9qqxSwSKgRJeZ9wygIaehbHFHFhcBaMDKpiZlBHyz
    rsnnlFXCb5s8HKn5LsUgGvB24L7sGNZP2CX7dhHov+YhD+jozLW2p9W4959Bz2Ei
    RmqDtmiXLnzqTpXbI+suyCsohKRg6Un0RC47+cpiVwHiXZAW+cn8eiNIjqbVgXLx
    KPpdzvvtTnOPlC7SQZSYmdunr3Bf9b77AiC/ZidstK36dRILKz7OA54=
    -----END CERTIFICATE-----
  server.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEArH2Ui08qyyTFIDumq18j8/GWi5Nb79IhfJAyno2xJUWwChMn
    CRmXOpBZnablKm4zqgj7n8W77FG7BC93B/Ge3N9NFLyWYcnCGFoKoJNVSHQFMZ/9
    F4n6Ke5xCzLDyWc/Ors/NnbeeSdJ9IMrl7csjjqGDc452t5jczcmLsgJGCJrI4Au
    rLBZnX853Sn9Uc9V8cBvlptspEaUkn8y0lDHV0hGK+vyn1ScysLnOW+QXEhQr5JD
    LTyydnZ2k2RnYPebz24ZpzZQzvfXLDUcrHRseff+zTQziFkV971+WnBmPRL6U2O+
    O7l/QIxTiogl0+jTxG7zHDrUineHb7ZjhkEU3QIDAQABAoIBADyikJtAIyzyKhGg
    poBLm5nfbSp3jLQLTBY7om+2I3WUv8Nq5CgAxPajU71ls91si+DT85BAtETonjNk
    dBVozI2cOb52ZO7PO9nPnTjBUhN8JW9CbHff2v7ugPKMz+J21vVQaXI96wrv0sGP
    cr2MeK8ux30G57OWxaL02glL7FZ8/tusJMOytGBkPTYp7AqeOXXGK0QZhpGlS8iM
    glVIqJkesKKNnlbCtwMJoqIZ/cDyXhaD8AgCfgndkJhJ8RpNIpLVFlgX/44z4wx9
    Du9T2P07OeAaiWlZLw/EqinaJQ3zY57WzIpXDmFjDKZtAJsiTaoxQrUt7p2pdNnB
    kU3Ep8ECgYEA4DgQgSXFb/7Sem9bcb/BX8s8O1kwoibW6jhamY3DQC0a5b0Cv82V
    z60lputZyxUK5NqLfNSQcIC09T9o7x676V5yn5iL+zOF6Jh7fgkZw/Hh3X7gBLVk
    a+WpHQGhPRhCP9CtBz2PH/V9RTIF09+rb3MMRx0SiYhIV5APJSPxt+kCgYEAxPCD
    smsIP2SS8y87tTwcXKX0LhSxlvYdZeGYjfU+/TjPBALrxD/81NSIuEButpmUPU6j
    ASbt7fLfA4TNhFiQ2arV56dXa4Sa1SuxUHMCBl9Hz54QhAhgPzTRqgOe4TmzfICv
    yauyOHDB3wOd3dqEMGtEK5pXbsWOWFpCYPMwkNUCgYEA1xkRxEOO+BT2qFwh1qrF
    gPeAjdLPVA98h2+Ogta7o9phflnnxEceW//YKhyHpMpIDCoYPKXS9wqSDuBI83SB
    gqyHu9FlIJRZ9zwo5E0ouZBXRNzNXdcCQnws01XX77tQ+tVe2J5WqqsgBPyrGInv
    ddhhw+sA+I2UEORzkwa7gdkCgYAM4SXbv0A01SD/InGnMp0wOfI0KUpL8yCNDyno
    7scFzHdNbdt5ZC3mxVeDpUMYUgbt03y5kJAy5ZVMJ51BMIGYmqGOmtUOxQdTNZ5N
    Aph5TjXmEBJIcDvLJmsn0UDMvfdNByV37PCk3ErxiM0EO0w11m4I4/kf12+tu4ln
    yb+9WQKBgQC8GhjX0TAH9dD6WHSivJ1wE6ZXISlHOGb3wuiul2JlDw6nGy5ldftY
    ezigt9PbpdQHv85aSdNQTL8xGzttqQPhyiAWqWCa3X19LzOd+O9BzK7+kaO8FNVk
    lewvSPk7QXpOdErtkOajaLgcotEJV05x0eoGhQlGRD8Q1MLUdjfpcg==
    -----END RSA PRIVATE KEY-----
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: postgres-ssl-file
