apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: kube-prom-stack
    meta.helm.sh/release-namespace: observability
  name: kube-prom-stack-grafana-nodeport
  namespace: observability
spec:
  selector:
    app.kubernetes.io/instance: kube-prom-stack
    app.kubernetes.io/name: grafana
  ports:
  - protocol: TCP
    port: 3000           # Service port
    targetPort: 3000   # Container port
    nodePort: 30300    # External port (must be within 30000-32767)
  type: NodePort
