---
- name: Install apt
  become: true
  apt:
    name: aptitude
    state: latest
    update_cache: true

- name: Check if Docker is already installed
  become: true
  shell: |
    if command -v docker > /dev/null 2>&1; then
      echo "Docker is installed"
    else
      echo "Docker is not installed"
    fi
  register: docker_installed
  changed_when: false

- name: Install required system packages
  become: true
  apt:
    pkg:
      - ca-certificates
      - curl
      - software-properties-common
    state: latest
    update_cache: true
  when: docker_installed.stdout.find("Docker is not installed") != -1

- name: Add Docker GPG apt Key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: docker_installed.stdout.find("Docker is not installed") != -1

- name: Add Docker Repository
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present
  when: docker_installed.stdout.find("Docker is not installed") != -1

- name: Update apt and install Docker
  become: true
  apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    update_cache: true
  when: docker_installed.stdout.find("Docker is not installed") != -1

- name: Add user to the Docker group
  become: true
  user:
    name: "{{ user.username }}"
    append: yes
    groups: docker
  when: docker_installed.stdout.find("Docker is not installed") != -1
